apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: kub
spec:
  selector:
    matchLabels:
      app: kub
  replicas: 3
  template:
    metadata:
      labels:
        app: kub
    spec:
      containers:
      - name: kub
        image: ping
        imagePullPolicy: Never #Refer local instead of download from public repo
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  # Uncomment the below line to create a Headless Service
  # clusterIP: None
  selector:
    app: kub
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000